// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOWHp7jy1yvGJK_fK3bW0DhMXg9pYGxWU',
    appId: '1:199895097353:web:7c0cd162aafb3aef8798d8',
    messagingSenderId: '199895097353',
    projectId: 'movie-booking-app-c9189',
    authDomain: 'movie-booking-app-c9189.firebaseapp.com',
    storageBucket: 'movie-booking-app-c9189.appspot.com',
    measurementId: 'G-V98CJ3DL2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFG7slLMwvaAMZ0mvWX4Gfx034pocPDpk',
    appId: '1:199895097353:android:c46ed97dd3cd9a718798d8',
    messagingSenderId: '199895097353',
    projectId: 'movie-booking-app-c9189',
    storageBucket: 'movie-booking-app-c9189.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRDWjsu017L9oPyP-n9VgyuXQX5fC_h_g',
    appId: '1:199895097353:ios:b89652cbdebcbadc8798d8',
    messagingSenderId: '199895097353',
    projectId: 'movie-booking-app-c9189',
    storageBucket: 'movie-booking-app-c9189.appspot.com',
    iosClientId: '199895097353-62cr8omuf8k6p6k77t9rr0t856d4s6e0.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRDWjsu017L9oPyP-n9VgyuXQX5fC_h_g',
    appId: '1:199895097353:ios:b89652cbdebcbadc8798d8',
    messagingSenderId: '199895097353',
    projectId: 'movie-booking-app-c9189',
    storageBucket: 'movie-booking-app-c9189.appspot.com',
    iosClientId: '199895097353-62cr8omuf8k6p6k77t9rr0t856d4s6e0.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieBookingApp',
  );
}
